### PR TITLE
bump version to v0.5.0rc1

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by jGaboardi** [comment]
@knaaptime @gegen07 The pre-release I cut yesterday didn't trigger anything from `conda-forge`, so doing this manually. Maybe pre-releases are caught for automatic PRs by the conda-forge bot?

**Comment by jGaboardi** [comment]
failure [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=641099&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d); need to investigate...

**Comment by jGaboardi** [comment]
Seems that [line 117](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=641099&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) (having trouble with the permalink for some reason) is saying [`requirements_notebooks.txt`](https://github.com/pysal/spopt/blob/main/requirements_notebooks.txt) exist?

@ocefpaf Any chance I could get assistance debugging this?

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@jGaboardi that file is not in the source distribution. You can either patch it here b/c you don't really need it. Or do a new release that include that file.

**Comment by jGaboardi** [comment]
> @jGaboardi that file is not in the source distribution. You can either patch it here b/c you don't really need it. Or do a new release that include that file.

Thanks a ton @ocefpaf! I knew it must have been a simple oversight on my part!

**Pull request closed without merging**
